SECRET_KEY = 'INSERT KEY HERE'

# ----------- MESSAGING -------------
MESSAGING_HOST = 'INSERT HOST HERE'
MESSAGING_PORT = 5671
MESSAGING_USER = 'INSERT UN HERE'
MESSAGING_EXCHANGE_NAME = 'INSERT NAME HERE'
MESSAGING_SSL = True
MESSAGING_PASSWORD = '@todo INSERT KEY HERE'